controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # Only define the TYPES here
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# Define the PARAMETERS in their own separate section
diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.34
    wheel_radius: 0.05

    use_stamped_vel: false

# (Optional) If you had params for the broadcaster, they would go here
# joint_broad:
#   ros__parameters: